"""Named, fixed-budget sampler profiles for CSDNet de novo evaluation."""

from __future__ import annotations


# Sequence-length bounds include BOS and EOS. The corresponding molecular body
# ranges are therefore two tokens shorter.
SAMPLER_PROFILES = {
    # Native sampler for ElasticCSDNet. Length is generated by the learned
    # insertion process, while top-probability commitment and a moderate
    # nucleus filter follow the strongest released LoFlex decoding setup.
    "elastic_loflex": {
        "temperature_start": 1.00,
        "temperature_end": 1.00,
        "temperature_power": 1.00,
        "gumbel_scale": 1.00,
        "top_k": 0,
        "top_p": 0.50,
        "length_min": 0,
        "length_max": 256,
        "length_explore_fraction": 0.00,
        "length_batching": "random",
        "remask_power": 1.00,
    },
    "baseline": {
        "temperature_start": 1.50,
        "temperature_end": 0.25,
        "temperature_power": 1.50,
        "gumbel_scale": 1.00,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 0,
        "length_max": 0,
        "length_explore_fraction": 0.00,
        "length_batching": "random",
        "remask_power": 1.00,
    },
    # Isolates the length intervention while preserving the original sampler.
    "length_quality": {
        "temperature_start": 1.50,
        "temperature_end": 0.25,
        "temperature_power": 1.50,
        "gumbel_scale": 1.00,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 27,
        "length_max": 47,
        "length_explore_fraction": 0.05,
        "length_batching": "random",
        "remask_power": 1.00,
    },
    # Historical low-entropy approximation. This does not reproduce GenMol's
    # one-token-at-a-time confidence unmasking rule.
    "genmol_quality": {
        "temperature_start": 0.50,
        "temperature_end": 0.50,
        "temperature_power": 1.00,
        "gumbel_scale": 0.50,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 32,
        "length_max": 47,
        "length_explore_fraction": 0.05,
        "length_batching": "random",
        "remask_power": 1.00,
    },
    # More conservative confidence confirmation with a small nucleus filter.
    "confidence_quality": {
        "temperature_start": 1.00,
        "temperature_end": 0.10,
        "temperature_power": 1.25,
        "gumbel_scale": 0.25,
        "top_k": 0,
        "top_p": 0.97,
        "length_min": 27,
        "length_max": 47,
        "length_explore_fraction": 0.05,
        "length_batching": "random",
        "remask_power": 1.00,
    },
    # Middle ground intended to preserve more uniqueness and diversity.
    "balanced_quality": {
        "temperature_start": 1.20,
        "temperature_end": 0.15,
        "temperature_power": 1.50,
        "gumbel_scale": 0.60,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 27,
        "length_max": 52,
        "length_explore_fraction": 0.10,
        "length_batching": "random",
        "remask_power": 1.00,
    },
    # ProMax profiles share the complete external ZINC250K length prior. The
    # evaluator validates that the prior was re-tokenized in CSDNet atomic
    # token space. Sorting changes padding cost, not the sampled distribution.
    "promax_balanced": {
        "temperature_start": 1.50,
        "temperature_end": 0.25,
        "temperature_power": 1.50,
        "gumbel_scale": 1.00,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 0,
        "length_max": 0,
        "length_explore_fraction": 0.00,
        "length_batching": "sorted",
        "remask_power": 1.00,
    },
    # A moderate entropy reduction and faster context exposure target the
    # benchmark's unique-quality count without property conditioning or
    # post-generation oracle filtering.
    "promax_quality": {
        "temperature_start": 1.20,
        "temperature_end": 0.15,
        "temperature_power": 1.50,
        "gumbel_scale": 0.65,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 0,
        "length_max": 0,
        "length_explore_fraction": 0.00,
        "length_batching": "sorted",
        "remask_power": 1.35,
    },
    # Higher categorical entropy and slower context exposure keep alternatives
    # alive longer, defining the diversity endpoint of the same protocol.
    "promax_diversity": {
        "temperature_start": 1.80,
        "temperature_end": 0.35,
        "temperature_power": 1.25,
        "gumbel_scale": 1.35,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 0,
        "length_max": 0,
        "length_explore_fraction": 0.00,
        "length_batching": "sorted",
        "remask_power": 0.80,
    },
    # Clean ablation: only categorical temperature depends on the requested
    # atomic-token length. Confidence randomness and remasking stay fixed.
    "promax_length_temperature": {
        "temperature_start": 1.20,
        "temperature_end": 0.15,
        "temperature_power": 1.50,
        "gumbel_scale": 1.00,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 0,
        "length_max": 0,
        "length_explore_fraction": 0.00,
        "length_batching": "sorted",
        "remask_power": 1.00,
        "length_adaptive": True,
        "adaptive_length_low": 30.0,
        "adaptive_length_high": 38.0,
        "adaptive_temperature_start_short": 1.80,
        "adaptive_temperature_end_short": 0.35,
        "adaptive_temperature_power_short": 1.25,
        "adaptive_gumbel_scale_short": 1.00,
        "adaptive_remask_power_short": 1.00,
    },
    # Full length-conditioned entropy control. Short sequences retain the
    # exploratory endpoint; longer sequences smoothly approach refinement.
    "promax_length_entropy": {
        "temperature_start": 1.20,
        "temperature_end": 0.15,
        "temperature_power": 1.50,
        "gumbel_scale": 0.65,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 0,
        "length_max": 0,
        "length_explore_fraction": 0.00,
        "length_batching": "sorted",
        "remask_power": 1.35,
        "length_adaptive": True,
        "adaptive_length_low": 30.0,
        "adaptive_length_high": 38.0,
        "adaptive_temperature_start_short": 1.80,
        "adaptive_temperature_end_short": 0.35,
        "adaptive_temperature_power_short": 1.25,
        "adaptive_gumbel_scale_short": 1.35,
        "adaptive_remask_power_short": 0.80,
    },
    # Clean confidence ablation: token draws retain the successful
    # length-conditioned entropy schedule, while commitment confidence is
    # measured under the untempered model posterior.
    "promax_confidence_decoupled": {
        "temperature_start": 1.20,
        "temperature_end": 0.15,
        "temperature_power": 1.50,
        "gumbel_scale": 0.65,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 0,
        "length_max": 0,
        "length_explore_fraction": 0.00,
        "length_batching": "sorted",
        "remask_power": 1.35,
        "length_adaptive": True,
        "adaptive_length_low": 30.0,
        "adaptive_length_high": 38.0,
        "adaptive_temperature_start_short": 1.80,
        "adaptive_temperature_end_short": 0.35,
        "adaptive_temperature_power_short": 1.25,
        "adaptive_gumbel_scale_short": 1.35,
        "adaptive_remask_power_short": 0.80,
        "confidence_temperature": 1.0,
        "progressive_commit": False,
    },
    # GenMol/PMO-style progressive commitment. Confirmed tokens remain fixed
    # until confidence remasking explicitly returns them to the masked state.
    "promax_confidence_progressive": {
        "temperature_start": 1.20,
        "temperature_end": 0.15,
        "temperature_power": 1.50,
        "gumbel_scale": 0.65,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 0,
        "length_max": 0,
        "length_explore_fraction": 0.00,
        "length_batching": "sorted",
        "remask_power": 1.35,
        "length_adaptive": True,
        "adaptive_length_low": 30.0,
        "adaptive_length_high": 38.0,
        "adaptive_temperature_start_short": 1.80,
        "adaptive_temperature_end_short": 0.35,
        "adaptive_temperature_power_short": 1.25,
        "adaptive_gumbel_scale_short": 1.35,
        "adaptive_remask_power_short": 0.80,
        "confidence_temperature": 1.0,
        "progressive_commit": True,
    },
    # Missing cell of the confidence x commitment factorial: preserve the
    # successful temperature-coupled confidence score and change only token
    # commitment semantics relative to promax_length_entropy.
    "promax_progressive_coupled": {
        "temperature_start": 1.20,
        "temperature_end": 0.15,
        "temperature_power": 1.50,
        "gumbel_scale": 0.65,
        "top_k": 0,
        "top_p": 1.00,
        "length_min": 0,
        "length_max": 0,
        "length_explore_fraction": 0.00,
        "length_batching": "sorted",
        "remask_power": 1.35,
        "length_adaptive": True,
        "adaptive_length_low": 30.0,
        "adaptive_length_high": 38.0,
        "adaptive_temperature_start_short": 1.80,
        "adaptive_temperature_end_short": 0.35,
        "adaptive_temperature_power_short": 1.25,
        "adaptive_gumbel_scale_short": 1.35,
        "adaptive_remask_power_short": 0.80,
        "confidence_temperature": 0.0,
        "progressive_commit": True,
    },
}

# Exact runtime ablation of the production ElasticCSDNet sampler. The sampling
# schedule is copied unchanged; only the FSM repair gate is disabled below.
SAMPLER_PROFILES["elastic_loflex_fsm_off"] = {
    **SAMPLER_PROFILES["elastic_loflex"],
}

# Factorial constraint-system ablation. All four profiles retain exactly the
# same checkpoint-facing sampler schedule. Only the structural/valence FSM and
# online RDKit repair gates differ; terminal RDKit metrics remain evaluation
# only because strict sanitization is disabled in every condition.
for _constraint_profile in (
    "elastic_loflex_constraint_none",
    "elastic_loflex_constraint_fsm_only",
    "elastic_loflex_constraint_rdkit_only",
    "elastic_loflex_constraint_full",
):
    SAMPLER_PROFILES[_constraint_profile] = {
        **SAMPLER_PROFILES["elastic_loflex"],
    }

# Backward-compatible aliases for the earlier two-endpoint screen.
SAMPLER_PROFILES["elastic_loflex_full_constraints"] = {
    **SAMPLER_PROFILES["elastic_loflex"],
}
SAMPLER_PROFILES["elastic_loflex_unconstrained"] = {
    **SAMPLER_PROFILES["elastic_loflex"],
}
SAMPLER_RUNTIME_OVERRIDES = {
    "elastic_loflex_fsm_off": {"disable_fsm_check": True},
    "elastic_loflex_constraint_none": {
        "disable_fsm_check": True,
        "disable_rdkit_kekulize_check": True,
        "strict_final_sanitize": False,
    },
    "elastic_loflex_constraint_fsm_only": {
        "disable_fsm_check": False,
        "disable_rdkit_kekulize_check": True,
        "strict_final_sanitize": False,
    },
    "elastic_loflex_constraint_rdkit_only": {
        "disable_fsm_check": True,
        "disable_rdkit_kekulize_check": False,
        "strict_final_sanitize": False,
    },
    "elastic_loflex_constraint_full": {
        "disable_fsm_check": False,
        "disable_rdkit_kekulize_check": False,
        "strict_final_sanitize": False,
    },
    "elastic_loflex_full_constraints": {
        "disable_fsm_check": False,
        "disable_rdkit_kekulize_check": False,
        "strict_final_sanitize": False,
    },
    "elastic_loflex_unconstrained": {
        "disable_fsm_check": True,
        "disable_rdkit_kekulize_check": True,
        "strict_final_sanitize": False,
    },
}

# Training-free local refinement: preserve the strongest observed de novo
# profile, then revisit low-confidence contiguous spans. Acceptance uses only
# model pseudo-likelihood and the existing FSM, never QED/SA or dataset labels.
SAMPLER_PROFILES["promax_block_refine"] = {
    **SAMPLER_PROFILES["promax_length_entropy"],
    "block_refine_steps": 32,
    "block_refine_span_max": 4,
    "block_refine_candidates": 3,
    "block_refine_temperature": 0.75,
    "block_refine_accept_margin": 0.0,
}

# Refinement-trained checkpoints see a fully filled draft and an explicit
# assumed corruption rate. Only higher-likelihood low-confidence tokens are
# changed; FSM gating and exact final sanitization prevent structural regressions.
SAMPLER_PROFILES["promax_all_position_refine"] = {
    **SAMPLER_PROFILES["promax_length_entropy"],
    "all_position_refine_steps": 24,
    "all_position_corruption_start": 0.25,
    "all_position_corruption_end": 0.05,
    "all_position_corruption_power": 1.50,
    "all_position_max_edits": 4,
    "all_position_min_logprob_gain": 0.05,
}

# Conservative final sampler. Full-position logits nominate one coordinate;
# an independent masked-context conditional verifies it before any edit is
# committed. The trust region prevents cycles and distribution collapse.
SAMPLER_PROFILES["promax_verified_refine"] = {
    **SAMPLER_PROFILES["promax_length_entropy"],
    "all_position_refine_steps": 8,
    "all_position_corruption_start": 0.20,
    "all_position_corruption_end": 0.05,
    "all_position_corruption_power": 1.50,
    "all_position_max_edits": 1,
    "all_position_min_logprob_gain": 0.05,
    "all_position_verify_masked": True,
    "all_position_verify_min_logprob_gain": 0.25,
    "all_position_prevent_revisit": True,
    "all_position_patience": 2,
    "all_position_rdkit_each_step": True,
}

# Progressive-coupled generation with reversible confidence. Visible tokens
# are rescored only after the remaining mask ratio enters the corruption range
# covered by refinement training. Sampling remains restricted to masked
# positions, so refreshing confidence never rewrites a token directly.
SAMPLER_PROFILES["promax_progressive_refresh"] = {
    **SAMPLER_PROFILES["promax_progressive_coupled"],
    "progressive_refresh_confidence": True,
    "progressive_refresh_start": 0.50,
    # Current-token posterior probability is already the Bayes confidence for
    # tokenwise 0-1 error. Keep the alternative-gain term disabled to avoid
    # double-counting the same posterior evidence.
    "progressive_refresh_gain_weight": 0.00,
}

# Clean tail-refinement ablation: preserve the observed progressive-coupled
# trajectory exactly, then permit only independently verified single-token
# improvements.
SAMPLER_PROFILES["promax_progressive_verified"] = {
    **SAMPLER_PROFILES["promax_progressive_coupled"],
    "all_position_refine_steps": 8,
    "all_position_corruption_start": 0.20,
    "all_position_corruption_end": 0.05,
    "all_position_corruption_power": 1.50,
    "all_position_max_edits": 1,
    "all_position_max_total_edits": 2,
    "all_position_min_logprob_gain": 0.05,
    "all_position_verify_masked": True,
    "all_position_verify_min_logprob_gain": 0.25,
    "all_position_prevent_revisit": True,
    "all_position_patience": 2,
    "all_position_rdkit_each_step": True,
}

# Full progressive consistency sampler. The main trajectory combines coupled
# confidence, a monotone mask-budget schedule, and reversible commitment; the
# terminal trust region accepts an edit only when masked context, FSM, and
# RDKit agree.
SAMPLER_PROFILES["promax_progressive_consistency"] = {
    **SAMPLER_PROFILES["promax_progressive_verified"],
    "progressive_refresh_confidence": True,
    "progressive_refresh_start": 0.50,
    "progressive_refresh_gain_weight": 0.00,
}

# Evidence-driven confidence calibration. The successful untempered
# commitment rule is retained for short requested sequences, then smoothly
# transitions to progressive-coupled confidence for longer sequences. Token
# draws, the empirical length prior, and the fixed output budget are unchanged.
SAMPLER_PROFILES["promax_progressive_length_coupled"] = {
    **SAMPLER_PROFILES["promax_progressive_coupled"],
    "confidence_length_adaptive": True,
    "adaptive_confidence_length_low": 28.0,
    "adaptive_confidence_length_high": 34.0,
    "adaptive_confidence_temperature_short": 1.0,
}

# Fragment-only conditional sampler. Total molecular length calibrates token
# sampling, while the editable dimension calibrates confidence commitment.
# A short terminal pass uses the trajectory-refinement checkpoint to correct
# visible tokens inside the generated region; supplied fragment tokens remain
# immutable and no property oracle participates in acceptance.
SAMPLER_PROFILES["promax_fragment_conditional_refine"] = {
    **SAMPLER_PROFILES["promax_progressive_length_coupled"],
    "local_confidence_uses_editable_length": True,
    "all_position_refine_steps": 12,
    "all_position_corruption_start": 0.25,
    "all_position_corruption_end": 0.05,
    "all_position_corruption_power": 1.50,
    "all_position_max_edits": 2,
    "all_position_max_total_edits": 6,
    "all_position_min_logprob_gain": 0.05,
    "all_position_verify_masked": False,
    "all_position_prevent_revisit": True,
    "all_position_patience": 2,
    "all_position_rdkit_each_step": True,
}

# Fragment infilling exposes a much smaller editable state than the complete
# molecular context.  Using total sequence length for every entropy control
# makes a long supplied scaffold force the generated span into the low-entropy
# endpoint, even when only a handful of positions are unknown.  This ablation
# keeps the complete context visible but calibrates sampling to editable size.
SAMPLER_PROFILES["promax_fragment_editable_refine"] = {
    **SAMPLER_PROFILES["promax_fragment_conditional_refine"],
    "local_sampling_uses_editable_length": True,
    "local_adaptive_length_low": 12.0,
    "local_adaptive_length_high": 24.0,
}

# A masked-proposal terminal pass matches the original denoising objective more
# closely than asking a fully visible draft to contradict itself.  Positions
# are nominated only inside the generated span and accepted using model
# likelihood plus the existing FSM/RDKit guards; no property oracle is used.
SAMPLER_PROFILES["promax_fragment_masked_refine"] = {
    **SAMPLER_PROFILES["promax_fragment_editable_refine"],
    "all_position_refine_steps": 8,
    "all_position_max_edits": 1,
    "all_position_max_total_edits": 4,
    "all_position_min_logprob_gain": 0.10,
    "all_position_proposal_masked": True,
    "all_position_verify_masked": False,
}

# Task-level local sampling keeps the adapter's operator semantics intact.
# Total molecular length still controls token sampling, but confidence is
# calibrated by the number of positions that can actually be changed.  The
# temperature schedule is scaled from the operator-provided values instead of
# replacing them with the de novo absolute temperatures.
SAMPLER_PROFILES["promax_task_adaptive_local"] = {
    **SAMPLER_PROFILES["promax_progressive_length_coupled"],
    "local_confidence_uses_editable_length": True,
    "local_temperature_mode": "operator_scaled",
}

# Conservative refinement arm for task optimizers.  Only originally editable
# positions may change.  Independent masked-context verification and RDKit/FSM
# checks protect already-satisfied task constraints while exposing the visible-
# token correction ability of trajectory-refinement checkpoints.
SAMPLER_PROFILES["promax_task_adaptive_refine"] = {
    **SAMPLER_PROFILES["promax_task_adaptive_local"],
    "all_position_refine_steps": 8,
    "all_position_corruption_start": 0.20,
    "all_position_corruption_end": 0.05,
    "all_position_corruption_power": 1.50,
    "all_position_max_edits": 1,
    "all_position_max_total_edits": 2,
    "all_position_min_logprob_gain": 0.05,
    "all_position_verify_masked": True,
    "all_position_verify_min_logprob_gain": 0.20,
    "all_position_prevent_revisit": True,
    "all_position_patience": 2,
    "all_position_rdkit_each_step": True,
}


_LENGTH_ADAPTIVE_DEFAULTS = {
    "length_adaptive": False,
    "local_confidence_uses_editable_length": False,
    "local_temperature_mode": "profile_absolute",
    "adaptive_length_low": 30.0,
    "adaptive_length_high": 38.0,
    "adaptive_temperature_start_short": 1.80,
    "adaptive_temperature_end_short": 0.35,
    "adaptive_temperature_power_short": 1.25,
    "adaptive_gumbel_scale_short": 1.00,
    "adaptive_remask_power_short": 1.00,
}
for _values in SAMPLER_PROFILES.values():
    for _key, _value in _LENGTH_ADAPTIVE_DEFAULTS.items():
        _values.setdefault(_key, _value)

_ALL_POSITION_REFINEMENT_DEFAULTS = {
    "all_position_refine_steps": 0,
    "all_position_corruption_start": 0.25,
    "all_position_corruption_end": 0.05,
    "all_position_corruption_power": 1.50,
    "all_position_max_edits": 4,
    "all_position_max_total_edits": 0,
    "all_position_min_logprob_gain": 0.05,
    "all_position_verify_masked": False,
    "all_position_verify_min_logprob_gain": 0.25,
    "all_position_prevent_revisit": False,
    "all_position_patience": 0,
    "all_position_rdkit_each_step": False,
}
for _values in SAMPLER_PROFILES.values():
    for _key, _value in _ALL_POSITION_REFINEMENT_DEFAULTS.items():
        _values.setdefault(_key, _value)

# Local conditional controls deliberately stay outside the public de novo CLI
# argument surface.  They are nevertheless materialized on every named profile
# so profile dictionaries remain auditable and shape-compatible.
_LOCAL_CONDITIONAL_DEFAULTS = {
    "local_sampling_uses_editable_length": False,
    "local_adaptive_length_low": 12.0,
    "local_adaptive_length_high": 24.0,
    "all_position_proposal_masked": False,
}
for _values in SAMPLER_PROFILES.values():
    for _key, _value in _LOCAL_CONDITIONAL_DEFAULTS.items():
        _values.setdefault(_key, _value)

_BLOCK_REFINEMENT_DEFAULTS = {
    "block_refine_steps": 0,
    "block_refine_span_max": 4,
    "block_refine_candidates": 3,
    "block_refine_temperature": 0.75,
    "block_refine_accept_margin": 0.0,
}
for _values in SAMPLER_PROFILES.values():
    for _key, _value in _BLOCK_REFINEMENT_DEFAULTS.items():
        _values.setdefault(_key, _value)

_CONFIDENCE_PLANNING_DEFAULTS = {
    # Zero preserves the existing coupled confidence score exactly.
    "confidence_temperature": 0.0,
    "confidence_length_adaptive": False,
    "adaptive_confidence_length_low": 28.0,
    "adaptive_confidence_length_high": 34.0,
    "adaptive_confidence_temperature_short": 1.0,
    "progressive_commit": False,
    "progressive_refresh_confidence": False,
    "progressive_refresh_start": 0.50,
    "progressive_refresh_gain_weight": 0.0,
}
for _values in SAMPLER_PROFILES.values():
    for _key, _value in _CONFIDENCE_PLANNING_DEFAULTS.items():
        _values.setdefault(_key, _value)


def apply_sampler_profile(args):
    """Apply a named profile to an argparse namespace in place."""
    name = getattr(args, "sampler_profile", "custom")
    if name == "custom":
        return args
    if name not in SAMPLER_PROFILES:
        choices = ", ".join(sorted(SAMPLER_PROFILES))
        raise ValueError(f"Unknown sampler profile {name!r}; choose from {choices}")
    for key, value in SAMPLER_PROFILES[name].items():
        setattr(args, key, value)
    for key, value in SAMPLER_RUNTIME_OVERRIDES.get(name, {}).items():
        setattr(args, key, value)
    return args


def add_length_adaptive_arguments(parser):
    """Register the shared adaptive sampler CLI surface on an evaluator."""
    parser.add_argument("--length_adaptive", action="store_true")
    parser.add_argument("--adaptive_length_low", type=float, default=30.0)
    parser.add_argument("--adaptive_length_high", type=float, default=38.0)
    parser.add_argument("--adaptive_temperature_start_short", type=float, default=1.8)
    parser.add_argument("--adaptive_temperature_end_short", type=float, default=0.35)
    parser.add_argument("--adaptive_temperature_power_short", type=float, default=1.25)
    parser.add_argument("--adaptive_gumbel_scale_short", type=float, default=1.0)
    parser.add_argument("--adaptive_remask_power_short", type=float, default=1.0)
    return parser


def length_adaptive_kwargs(args):
    """Return the adaptive arguments shared by every de novo entrypoint."""
    keys = (
        "length_adaptive",
        "adaptive_length_low",
        "adaptive_length_high",
        "adaptive_temperature_start_short",
        "adaptive_temperature_end_short",
        "adaptive_temperature_power_short",
        "adaptive_gumbel_scale_short",
        "adaptive_remask_power_short",
    )
    return {key: getattr(args, key) for key in keys}


def add_confidence_planning_arguments(parser):
    """Register confidence scoring and progressive commitment controls."""
    parser.add_argument(
        "--confidence_temperature",
        type=float,
        default=0.0,
        help=(
            "Independent commitment-confidence temperature; zero reuses the "
            "temperature-scaled sampling distribution."
        ),
    )
    parser.add_argument("--confidence_length_adaptive", action="store_true")
    parser.add_argument(
        "--adaptive_confidence_length_low",
        type=float,
        default=28.0,
    )
    parser.add_argument(
        "--adaptive_confidence_length_high",
        type=float,
        default=34.0,
    )
    parser.add_argument(
        "--adaptive_confidence_temperature_short",
        type=float,
        default=1.0,
    )
    parser.add_argument("--progressive_commit", action="store_true")
    parser.add_argument("--progressive_refresh_confidence", action="store_true")
    parser.add_argument(
        "--progressive_refresh_start",
        type=float,
        default=0.50,
        help=(
            "Refresh visible-token confidence once the remaining mask ratio "
            "is at or below this value."
        ),
    )
    parser.add_argument(
        "--progressive_refresh_gain_weight",
        type=float,
        default=0.0,
        help=(
            "Additional penalty for a visible token when the refinement head "
            "prefers an alternative token."
        ),
    )
    return parser


def confidence_planning_kwargs(args):
    """Return confidence-planning arguments shared by de novo entrypoints."""
    keys = tuple(_CONFIDENCE_PLANNING_DEFAULTS)
    return {key: getattr(args, key) for key in keys}


def add_block_refinement_arguments(parser):
    """Register training-free low-confidence block refinement controls."""
    parser.add_argument("--block_refine_steps", type=int, default=0)
    parser.add_argument("--block_refine_span_max", type=int, default=4)
    parser.add_argument("--block_refine_candidates", type=int, default=3)
    parser.add_argument("--block_refine_temperature", type=float, default=0.75)
    parser.add_argument("--block_refine_accept_margin", type=float, default=0.0)
    return parser


def block_refinement_kwargs(args):
    """Return block-refinement arguments shared by de novo entrypoints."""
    return {
        key: getattr(args, key)
        for key in _BLOCK_REFINEMENT_DEFAULTS
    }


def add_all_position_refinement_arguments(parser):
    """Register refinement-trained all-position denoising controls."""
    parser.add_argument("--all_position_refine_steps", type=int, default=0)
    parser.add_argument(
        "--all_position_corruption_start",
        type=float,
        default=0.25,
    )
    parser.add_argument(
        "--all_position_corruption_end",
        type=float,
        default=0.05,
    )
    parser.add_argument(
        "--all_position_corruption_power",
        type=float,
        default=1.50,
    )
    parser.add_argument("--all_position_max_edits", type=int, default=4)
    parser.add_argument(
        "--all_position_max_total_edits",
        type=int,
        default=0,
        help="Maximum accepted edits per molecule; zero disables the cap.",
    )
    parser.add_argument(
        "--all_position_min_logprob_gain",
        type=float,
        default=0.05,
    )
    parser.add_argument("--all_position_verify_masked", action="store_true")
    parser.add_argument(
        "--all_position_verify_min_logprob_gain",
        type=float,
        default=0.25,
    )
    parser.add_argument("--all_position_prevent_revisit", action="store_true")
    parser.add_argument("--all_position_patience", type=int, default=0)
    parser.add_argument("--all_position_rdkit_each_step", action="store_true")
    return parser


def all_position_refinement_kwargs(args):
    """Return all-position refinement arguments for the shared sampler."""
    return {
        key: getattr(args, key)
        for key in _ALL_POSITION_REFINEMENT_DEFAULTS
    }
